version: "3"
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: yoshinoya_copy_paste_generator-image
    container_name: yoshinoya_copy_paste_generator-container
    tty: true
    env_file: ../.env # shellスクリプト内でも環境変数として使用するため
